Repository CambioML/any-parser, pull requests merged in 2025-01, with the labels that each got.

#77 Add notebook example for Batch API
  .gitignore
  README.md
  examples/parse_batch_api.ipynb
  examples/parse_batch_fetch.py
  examples/parse_batch_upload.py
Labels: Review effort [1-5]: 3

#78 Bump up version to 0.0.20.
  any_parser/__init__.py
  pyproject.toml
Labels: Review effort [1-5]: 1

#79 feat: add csv feature to extract_tables
  any_parser/any_parser.py
  examples/extract_tables.ipynb
Labels: Review effort [1-5]: 4
